name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install -y opencl-headers
    - name: abc
      run: sudo mkdir -p /usr/lib/x86_64-linux-gnu/ && sudo ln -s /usr/lib/libOpenCL.so /usr/lib/x86_64-linux-gnu/libOpenCL.so
    - name: make
      run: make all
